/* ============================================================================
 * tt_um_cpu_wrapper.v
 *
 * Tiny Tapeout top-level wrapper for the 8-bit CPU (cpu_merged_fixed.v).
 *
 * PROBLEM: the CPU's native interface (16-bit address bus + 8-bit data bus
 * + control lines) needs ~42 pins. Tiny Tapeout gives every project a fixed
 * 24 general-purpose I/O pins (8 ui_in, 8 uo_out, 8 uio), no matter how many
 * tiles or how the submission is funded.
 *
 * FIX: multiplex the address and data lines onto the 8 bidirectional uio
 * pins, exactly like an 8085 does for external memory. A small external
 * latch (e.g. two 74HC373s) on the PCB demultiplexes the shared bus back
 * into a real 16-bit address bus + 8-bit data bus for the external RAM/ROM.
 * The CPU core itself (cpu_merged_fixed.v) is NOT modified at all -- only
 * its clock is now generated by this wrapper's bus-cycle state machine, so
 * the CPU gets exactly one clock edge per completed external bus cycle.
 *
 * PIN MAP (fits the 24-pin budget exactly):
 *   uio[7:0]   -> AD[7:0]       shared address/data bus (bidirectional)
 *   uo_out[0]  -> ALE           address-latch-enable strobe (pulses twice
 *                                per bus cycle: once for the high byte,
 *                                once for the low byte -- see note below)
 *   uo_out[1]  -> RAM2BUS
 *   uo_out[2]  -> ROM2BUS
 *   uo_out[3]  -> GPU2BUS
 *   uo_out[4]  -> SVRAM
 *   uo_out[5]  -> SVGPU
 *   uo_out[6]  -> BUTTON2BUS
 *   uo_out[7]  -> BUTTONRST
 *   ui_in[0]   -> BUTTONPRESSED
 *   ui_in[7:1] -> unused / reserved for later
 *
 * EXTERNAL PCB GLUE NEEDED (outside the ASIC, not part of this file):
 *   Because there's only one ALE pin but two address bytes to latch, the
 *   PCB needs a small phase tracker: a 1-bit toggle flip-flop clocked by
 *   ALE, reset whenever (RAM2BUS | ROM2BUS | GPU2BUS) goes active (i.e. at
 *   the start of a new bus cycle). Its output selects which of the two
 *   374/373 latches captures the byte currently on AD[7:0] on each ALE
 *   pulse. This is standard multiplexed-bus glue (same idea as 8085-style
 *   memory interfacing) and lives on the demo board / breakout PCB, not on
 *   the die.
 *
 * TIMING NOTE: the CPU now advances one internal clock cycle for every 4
 * cycles of the chip's real `clk` (address-hi, address-lo, data, tick).
 * This trades raw speed for pin count -- unavoidable given the budget.
 *
 * TO CHECK BEFORE USE: `is_write` below assumes RAM2BUS/GPU2BUS being
 * asserted means the CPU is driving DATABUSOUT (a write). Confirm this
 * against the CU module's actual read/write convention for RAM2BUS,
 * ROM2BUS, and GPU2BUS before relying on it -- adjust if the polarity or
 * meaning differs (e.g. if ROM2BUS is always a read, it may need its own
 * handling since ROM is presumably read-only).
 * ============================================================================
 */

module tt_um_tiwarimanikanand007_cpu (
    input  wire [7:0] ui_in,    // Dedicated inputs
    output wire [7:0] uo_out,   // Dedicated outputs
    input  wire [7:0] uio_in,   // IOs: input path
    output wire [7:0] uio_out,  // IOs: output path
    output wire [7:0] uio_oe,   // IOs: enable (1 = drive out, 0 = input)
    input  wire       ena,      // high when design is enabled
    input  wire       clk,      // chip clock
    input  wire       rst_n     // active-low reset
);

    // ------------------------------------------------------------------
    // CPU core signals (CPU module is instantiated unmodified below)
    // ------------------------------------------------------------------
    wire [15:0] cpu_addr;
    wire [7:0]  cpu_data_out;
    reg  [7:0]  cpu_data_in;
    wire        cpu_button2bus, cpu_buttonrst;
    wire        cpu_gpu2bus, cpu_ram2bus, cpu_rom2bus;
    wire        cpu_svgpu, cpu_svram;
    reg         cpu_clk_r;
    wire        cpu_rst = ~rst_n;

    CPU cpu_core (
        .ADDRESSBUSOUT (cpu_addr),
        .BUTTON2BUS    (cpu_button2bus),
        .BUTTONPRESSED (ui_in[0]),
        .BUTTONRST     (cpu_buttonrst),
        .CLK           (cpu_clk_r),
        .DATABUSIN     (cpu_data_in),
        .DATABUSOUT    (cpu_data_out),
        .GPU2BUS       (cpu_gpu2bus),
        .RAM2BUS       (cpu_ram2bus),
        .ROM2BUS       (cpu_rom2bus),
        .RST           (cpu_rst),
        .SVGPU         (cpu_svgpu),
        .SVRAM         (cpu_svram)
    );

    // ------------------------------------------------------------------
    // Address/data bus multiplexing state machine (runs on chip `clk`)
    // ------------------------------------------------------------------
    localparam S_ADDR_HI = 2'd0,
               S_ADDR_LO = 2'd1,
               S_DATA    = 2'd2,
               S_TICK    = 2'd3;

    reg [1:0] state;
    reg       ale;
    reg [7:0] ad_out;
    reg       ad_oe;

    // See "TO CHECK BEFORE USE" above -- verify against the CU module.
    wire is_write = cpu_ram2bus | cpu_gpu2bus;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state     <= S_ADDR_HI;
            cpu_clk_r <= 1'b0;
            ale       <= 1'b0;
            ad_out    <= 8'h00;
            ad_oe     <= 1'b0;
            cpu_data_in <= 8'h00;
        end else if (ena) begin
            cpu_clk_r <= 1'b0;   // default: no CPU clock edge this cycle
            ale       <= 1'b0;   // default: ALE low unless a phase sets it

            case (state)
                S_ADDR_HI: begin
                    ad_out <= cpu_addr[15:8];
                    ad_oe  <= 1'b1;
                    ale    <= 1'b1;          // pulse 1: external glue latches hi byte
                    state  <= S_ADDR_LO;
                end

                S_ADDR_LO: begin
                    ad_out <= cpu_addr[7:0];
                    ad_oe  <= 1'b1;
                    ale    <= 1'b1;          // pulse 2: external glue latches lo byte
                    state  <= S_DATA;
                end

                S_DATA: begin
                    if (is_write) begin
                        ad_out <= cpu_data_out;
                        ad_oe  <= 1'b1;
                    end else begin
                        ad_oe       <= 1'b0; // release the bus, let external device drive it
                        cpu_data_in <= uio_in;
                    end
                    state <= S_TICK;
                end

                S_TICK: begin
                    cpu_clk_r <= 1'b1;       // give the CPU its one clock edge
                    state     <= S_ADDR_HI;
                end
            endcase
        end
    end

    // ------------------------------------------------------------------
    // Pin assignments
    // ------------------------------------------------------------------
    assign uio_out = ad_out;
    assign uio_oe  = {8{ad_oe}};

    assign uo_out[0] = ale;
    assign uo_out[1] = cpu_ram2bus;
    assign uo_out[2] = cpu_rom2bus;
    assign uo_out[3] = cpu_gpu2bus;
    assign uo_out[4] = cpu_svram;
    assign uo_out[5] = cpu_svgpu;
    assign uo_out[6] = cpu_button2bus;
    assign uo_out[7] = cpu_buttonrst;

    // Unused inputs -- silence lint warnings without affecting function
    wire _unused = &{ui_in[7:1], 1'b0};

endmodule
